In [36]:
import pandas as pd

print(f'pandas version = {pd.__version__}')
pd.Timestamp.now()

pandas version = 1.5.2

Timestamp('2023-01-18 10:58:37.552819')

In [37]:
df=pd.read_csv('https://github.com/prasertcbs/454_2566/raw/main/example/nutrients.csv', na_values=['t', "t'"])
df

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
0,Cows' milk,1 qt.,976,660,32.0,40.0,36.0,0,48.0,Dairy products
1,Milk skim,1 qt.,984,360,36.0,NaN,NaN,0,52.0,Dairy products
2,Buttermilk,1 cup,246,127,9.0,5.0,4.0,0,13.0,Dairy products
3,"Evaporated, undiluted",1 cup,252,345,16.0,20.0,18.0,0,24.0,Dairy products
4,Fortified milk,6 cups,"1,419","1,373",89.0,42.0,23.0,1.4,119.0,Dairy products
...,...,...,...,...,...,...,...,...,...,...
330,Fruit-flavored soda,12 oz.,346,161,0.0,0.0,0.0,0,42.0,"Drinks,Alcohol, Beverages"
331,Ginger ale,12 oz.,346,105,0.0,0.0,0.0,0,28.0,"Drinks,Alcohol, Beverages"
332,Root beer,12 oz.,346,140,0.0,0.0,0.0,0,35.0,"Drinks,Alcohol, Beverages"
333,Coffee,1 cup,230,3,NaN,0.0,0.0,0,1.0,"Drinks,Alcohol, Beverages"
334,Tea,1 cup,230,4,0.0,NaN,0.0,0,1.0,"Drinks,Alcohol, Beverages"

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Food      335 non-null    object
 1   Measure   335 non-null    object
 2   Grams     335 non-null    object
 3   Calories  334 non-null    object
 4   Protein   296 non-null    float64
 5   Fat       219 non-null    float64
 6   Sat.Fat   318 non-null    float64
 7   Fiber     309 non-null    object
 8   Carbs     322 non-null    float64
 9   Category  335 non-null    object
dtypes: float64(4), object(6)
memory usage: 26.3+ KB

In [39]:
df['Calories'].str.replace(',', '', regex=False).str.replace('-', '', regex=False)

0       660
1       360
2       127
3       345
4      1373
       ...
330     161
331     105
332     140
333       3
334       4
Name: Calories, Length: 335, dtype: object

In [40]:
# df['Calories']=pd.to_numeric(df['Calories'].str.replace(r'[,-]', '', regex=True))

In [41]:
# df['Calories'].mean()

In [42]:
df.columns

Index(['Food', 'Measure', 'Grams', 'Calories', 'Protein', 'Fat', 'Sat.Fat',
       'Fiber', 'Carbs', 'Category'],
      dtype='object')

In [43]:
cols=['Grams', 'Calories', 'Fiber']
for c in cols:
    df[c]=pd.to_numeric(df[c].str.replace(r'[,a\-]', '', regex=True))

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Food      335 non-null    object
 1   Measure   335 non-null    object
 2   Grams     335 non-null    int64
 3   Calories  334 non-null    float64
 4   Protein   296 non-null    float64
 5   Fat       219 non-null    float64
 6   Sat.Fat   318 non-null    float64
 7   Fiber     308 non-null    float64
 8   Carbs     322 non-null    float64
 9   Category  335 non-null    object
dtypes: float64(6), int64(1), object(3)
memory usage: 26.3+ KB

In [45]:
df.describe()

,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs
count,335.000000,334.000000,296.000000,219.000000,318.000000,308.000000,322.000000
mean,143.211940,191.251497,9.702703,13.063927,6.742138,2.576656,25.990994
std,138.668626,187.687099,18.575895,23.262671,18.896435,16.729786,36.189993
min,11.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000
25%,60.000000,75.000000,1.000000,1.000000,0.000000,0.000000,6.000000
50%,108.000000,133.500000,4.000000,8.000000,0.000000,0.400000,15.000000
75%,200.000000,250.000000,13.000000,14.000000,8.000000,1.200000,32.000000
max,1419.000000,1373.000000,232.000000,233.000000,234.000000,235.000000,236.000000

In [47]:
df.groupby('Category').describe()

                                 Grams                                         \
                                 count        mean         std    min     25%
Category
Breads, cereals, fastfood,grains  45.0  116.733333  109.076162   11.0   30.00
Dairy products                    28.0  264.714286  330.866299   17.0   85.00
Desserts, sweets                  29.0  102.000000   77.369245   12.0   40.00
Drinks,Alcohol, Beverages         12.0  273.666667  129.810585   28.0  202.50
Fats, Oils, Shortenings           14.0   49.642857   46.443692   14.0   14.00
Fish, Seafood                     19.0   99.578947   32.736856   85.0   85.00
Fruits A-F                        22.0  174.727273   88.438400   42.0  114.00
Fruits G-P                        28.0  193.285714   68.774919   60.0  136.25
Fruits R-Z                         8.0  246.625000  281.933091   88.0  100.00
Jams, Jellies                      8.0   52.750000   68.351507   20.0   20.00
Meat, Poultry                     30.0   92.800000   41.888522   16.0   85.00
Seeds and Nuts                    12.0   56.833333    9.740574   50.0   50.00
Soups                             10.0  249.500000    4.377975  240.0  250.00
Vegetables A-E                    28.0  131.607143   54.128338   40.0  100.00
Vegetables F-P                    14.0  123.214286   47.051819   50.0  100.00
Vegetables R-Z                    28.0  123.571429   61.689442   17.0  100.00

                                                        Calories              \
                                    50%     75%     max    count        mean
Category
Breads, cereals, fastfood,grains   75.0  191.00   454.0     45.0  264.911111
Dairy products                    189.0  248.50  1419.0     28.0  301.214286
Desserts, sweets                   90.0  135.00   300.0     29.0  227.862069
Drinks,Alcohol, Beverages         346.0  346.00   480.0     12.0   92.666667
Fats, Oils, Shortenings            15.0  107.50   112.0     14.0  259.214286
Fish, Seafood                      85.0  100.00   230.0     19.0  153.263158
Fruits A-F                        147.0  250.00   380.0     22.0  151.272727
Fruits G-P                        214.0  250.00   285.0     28.0  144.785714
Fruits R-Z                        131.5  237.75   925.0      8.0  153.500000
Jams, Jellies                      30.0   40.50   220.0      8.0  168.125000
Meat, Poultry                      85.0  100.00   235.0     30.0  266.633333
Seeds and Nuts                     50.0   70.00    70.0     12.0  340.750000
Soups                             250.0  250.00   255.0     10.0  119.100000
Vegetables A-E                    140.0  166.25   260.0     28.0   93.678571
Vegetables F-P                    115.0  147.50   210.0     14.0   50.785714
Vegetables R-Z                    100.0  160.00   240.0     27.0   99.777778

                                  ...  Fiber        Carbs             \
                                  ...    75%    max count       mean
Category                          ...
Breads, cereals, fastfood,grains  ...  1.600   67.5  45.0  45.755556
Dairy products                    ...  0.000    1.4  23.0  28.304348
Desserts, sweets                  ...  0.200   10.0  29.0  40.827586
Drinks,Alcohol, Beverages         ...  0.000    0.0  11.0  15.181818
Fats, Oils, Shortenings           ...  0.000  117.0   9.0  26.555556
Fish, Seafood                     ...  0.000  235.0  18.0  14.611111
Fruits A-F                        ...  2.000    6.6  22.0  36.909091
Fruits G-P                        ...  1.000    2.0  28.0  36.035714
Fruits R-Z                        ...  2.400    5.0   8.0  41.250000
Jams, Jellies                     ...  0.000    8.0   8.0  43.125000
Meat, Poultry                     ...  0.000    0.0  30.0   1.910000
Seeds and Nuts                    ...  1.925    3.1  12.0  11.666667
Soups                             ...  0.500    1.2  10.0  15.500000
Vegetables A-E                    ...  1.950    3.2  28.0  12.742857
Vegetables F-P                    ...  1.800    3.2  13.0  10.923077
Vegetables R-Z                    ...  1.500    3.2  28.0  16.392857


                                        std   min    25%   50%    75%    max
Category
Breads, cereals, fastfood,grains  51.442004   8.0  20.00  28.0  36.00  229.0
Dairy products                    27.601770   1.0   6.00  26.0  41.00  119.0
Desserts, sweets                  35.369548   0.0  23.00  31.0  48.00  199.0
Drinks,Alcohol, Beverages         16.892710   0.0   1.00   8.0  31.50   42.0
Fats, Oils, Shortenings           51.848604   0.0   0.00   0.0   2.00  118.0
Fish, Seafood                     55.337615   0.0   0.00   0.0   1.75  236.0
Fruits A-F                        36.902586   1.0  15.75  26.0  46.50  142.0
Fruits G-P                        29.313734   1.0  16.00  25.5  50.00  112.0
Fruits R-Z                        34.270979  10.0  13.50  27.0  65.50   98.0
Jams, Jellies                     67.868439  11.0  13.00  19.5  29.25  210.0
Meat, Poultry                      6.386535   0.0   0.00   0.0   0.00   32.0
Seeds and Nuts                     5.789227   7.0   8.00   9.5  13.00   26.0
Soups                              8.566732   0.0  11.25  13.5  21.00   30.0
Vegetables A-E                    13.402582   0.8   4.75   8.0  13.00   48.0
Vegetables F-P                    10.012172   2.0   5.00   7.0  13.00   38.0
Vegetables R-Z                    15.490354   2.0   8.00  11.0  21.25   80.0

[16 rows x 56 columns]

In [48]:
df['Protein'] < 0

0      False
1      False
2      False
3      False
4      False
       ...
330    False
331    False
332    False
333    False
334    False
Name: Protein, Length: 335, dtype: bool

In [49]:
df[df['Protein'] < 0]

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
141,French-fried,10 pieces,60,155.0,-1.0,7.0,3.0,0.4,20.0,Vegetables R-Z

In [51]:
df['Protein'].abs()

0      32.0
1      36.0
2       9.0
3      16.0
4      89.0
       ...
330     0.0
331     0.0
332     0.0
333     NaN
334     0.0
Name: Protein, Length: 335, dtype: float64

In [52]:
df.columns

Index(['Food', 'Measure', 'Grams', 'Calories', 'Protein', 'Fat', 'Sat.Fat',
       'Fiber', 'Carbs', 'Category'],
      dtype='object')

In [53]:
cols=['Grams', 'Calories', 'Protein', 'Fat', 'Sat.Fat',
       'Fiber', 'Carbs']
for col in cols:
    df[col]=df[col].abs()

In [54]:
df.groupby('Category').describe()

                                 Grams                                         \
                                 count        mean         std    min     25%
Category
Breads, cereals, fastfood,grains  45.0  116.733333  109.076162   11.0   30.00
Dairy products                    28.0  264.714286  330.866299   17.0   85.00
Desserts, sweets                  29.0  102.000000   77.369245   12.0   40.00
Drinks,Alcohol, Beverages         12.0  273.666667  129.810585   28.0  202.50
Fats, Oils, Shortenings           14.0   49.642857   46.443692   14.0   14.00
Fish, Seafood                     19.0   99.578947   32.736856   85.0   85.00
Fruits A-F                        22.0  174.727273   88.438400   42.0  114.00
Fruits G-P                        28.0  193.285714   68.774919   60.0  136.25
Fruits R-Z                         8.0  246.625000  281.933091   88.0  100.00
Jams, Jellies                      8.0   52.750000   68.351507   20.0   20.00
Meat, Poultry                     30.0   92.800000   41.888522   16.0   85.00
Seeds and Nuts                    12.0   56.833333    9.740574   50.0   50.00
Soups                             10.0  249.500000    4.377975  240.0  250.00
Vegetables A-E                    28.0  131.607143   54.128338   40.0  100.00
Vegetables F-P                    14.0  123.214286   47.051819   50.0  100.00
Vegetables R-Z                    28.0  123.571429   61.689442   17.0  100.00

                                                        Calories              \
                                    50%     75%     max    count        mean
Category
Breads, cereals, fastfood,grains   75.0  191.00   454.0     45.0  264.911111
Dairy products                    189.0  248.50  1419.0     28.0  301.214286
Desserts, sweets                   90.0  135.00   300.0     29.0  227.862069
Drinks,Alcohol, Beverages         346.0  346.00   480.0     12.0   92.666667
Fats, Oils, Shortenings            15.0  107.50   112.0     14.0  259.214286
Fish, Seafood                      85.0  100.00   230.0     19.0  153.263158
Fruits A-F                        147.0  250.00   380.0     22.0  151.272727
Fruits G-P                        214.0  250.00   285.0     28.0  144.785714
Fruits R-Z                        131.5  237.75   925.0      8.0  153.500000
Jams, Jellies                      30.0   40.50   220.0      8.0  168.125000
Meat, Poultry                      85.0  100.00   235.0     30.0  266.633333
Seeds and Nuts                     50.0   70.00    70.0     12.0  340.750000
Soups                             250.0  250.00   255.0     10.0  119.100000
Vegetables A-E                    140.0  166.25   260.0     28.0   93.678571
Vegetables F-P                    115.0  147.50   210.0     14.0   50.785714
Vegetables R-Z                    100.0  160.00   240.0     27.0   99.777778

                                  ...  Fiber        Carbs             \
                                  ...    75%    max count       mean
Category                          ...
Breads, cereals, fastfood,grains  ...  1.600   67.5  45.0  45.755556
Dairy products                    ...  0.000    1.4  23.0  28.304348
Desserts, sweets                  ...  0.200   10.0  29.0  40.827586
Drinks,Alcohol, Beverages         ...  0.000    0.0  11.0  15.181818
Fats, Oils, Shortenings           ...  0.000  117.0   9.0  26.555556
Fish, Seafood                     ...  0.000  235.0  18.0  14.611111
Fruits A-F                        ...  2.000    6.6  22.0  36.909091
Fruits G-P                        ...  1.000    2.0  28.0  36.035714
Fruits R-Z                        ...  2.400    5.0   8.0  41.250000
Jams, Jellies                     ...  0.000    8.0   8.0  43.125000
Meat, Poultry                     ...  0.000    0.0  30.0   1.910000
Seeds and Nuts                    ...  1.925    3.1  12.0  11.666667
Soups                             ...  0.500    1.2  10.0  15.500000
Vegetables A-E                    ...  1.950    3.2  28.0  12.742857
Vegetables F-P                    ...  1.800    3.2  13.0  10.923077
Vegetables R-Z                    ...  1.500    3.2  28.0  16.392857


                                        std   min    25%   50%    75%    max
Category
Breads, cereals, fastfood,grains  51.442004   8.0  20.00  28.0  36.00  229.0
Dairy products                    27.601770   1.0   6.00  26.0  41.00  119.0
Desserts, sweets                  35.369548   0.0  23.00  31.0  48.00  199.0
Drinks,Alcohol, Beverages         16.892710   0.0   1.00   8.0  31.50   42.0
Fats, Oils, Shortenings           51.848604   0.0   0.00   0.0   2.00  118.0
Fish, Seafood                     55.337615   0.0   0.00   0.0   1.75  236.0
Fruits A-F                        36.902586   1.0  15.75  26.0  46.50  142.0
Fruits G-P                        29.313734   1.0  16.00  25.5  50.00  112.0
Fruits R-Z                        34.270979  10.0  13.50  27.0  65.50   98.0
Jams, Jellies                     67.868439  11.0  13.00  19.5  29.25  210.0
Meat, Poultry                      6.386535   0.0   0.00   0.0   0.00   32.0
Seeds and Nuts                     5.789227   7.0   8.00   9.5  13.00   26.0
Soups                              8.566732   0.0  11.25  13.5  21.00   30.0
Vegetables A-E                    13.402582   0.8   4.75   8.0  13.00   48.0
Vegetables F-P                    10.012172   2.0   5.00   7.0  13.00   38.0
Vegetables R-Z                    15.490354   2.0   8.00  11.0  21.25   80.0

[16 rows x 56 columns]